import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux";
import OnAuthState from "@/components/OnAuthState";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <ReduxProvider>
          <OnAuthState>
            <main className="bg-neutral-100 flex items-center justify-center min-h-screen">{children}</main>
          </OnAuthState>
        </ReduxProvider>
      </body>
    </html>
  );
}
